<?php

return [
    [
        'key' => 'sales.carriers.egyptshipping',
        'name' => 'Egypt Shipping',
        'info' => 'Configure shipping rates per Egyptian governorate',
        'sort' => 3,
        'fields' => [
            [
                'name' => 'title',
                'title' => 'Title',
                'type' => 'text',
                'default' => 'Egypt Shipping',
                'depends' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => true,
                'locale_based' => true,
            ],
            [
                'name' => 'description',
                'title' => 'Description',
                'type' => 'textarea',
                'default' => 'Shipping within Egypt based on your governorate',
                'channel_based' => true,
                'locale_based' => true,
            ],
            [
                'name' => 'default_rate',
                'title' => 'Default Rate',
                'info' => 'Fallback rate if no specific governorate rate is set',
                'type' => 'text',
                'depends' => 'active:1',
                'validation' => 'required_if:active,1|numeric|min:0',
                'default' => '50',
                'channel_based' => true,
            ],
            [
                'name' => 'active',
                'title' => 'Status',
                'type' => 'boolean',
                'channel_based' => true,
                'locale_based' => false,
            ],
            // Governorate Rates - Each governorate has its own field
            [
                'name' => 'EG-ALX',
                'title' => 'Alexandria Rate (الإسكندرية)',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'EG-ASN',
                'title' => 'Aswan Rate (أسوان)',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'EG-AST',
                'title' => 'Asyut Rate (أسيوط)',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'EG-BA',
                'title' => 'Red Sea Rate (البحر الأحمر)',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'EG-BH',
                'title' => 'Beheira Rate (البحيرة)',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'EG-BNS',
                'title' => 'Beni Suef Rate (بني سويف)',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'EG-C',
                'title' => 'Cairo Rate (القاهرة)',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'EG-DK',
                'title' => 'Dakahlia Rate (الدقهلية)',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'EG-DT',
                'title' => 'Damietta Rate (دمياط)',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'EG-FYM',
                'title' => 'Fayoum Rate (الفيوم)',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'EG-GH',
                'title' => 'Gharbia Rate (الغربية)',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'EG-GZ',
                'title' => 'Giza Rate (الجيزة)',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'EG-IS',
                'title' => 'Ismailia Rate (الإسماعيلية)',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'EG-JS',
                'title' => 'South Sinai Rate (جنوب سيناء)',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'EG-KB',
                'title' => 'Qalyubia Rate (القليوبية)',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'EG-KFS',
                'title' => 'Kafr El Sheikh Rate (كفر الشيخ)',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'EG-KN',
                'title' => 'Qena Rate (قنا)',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'EG-LX',
                'title' => 'Luxor Rate (الأقصر)',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'EG-MN',
                'title' => 'Minya Rate (المنيا)',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'EG-MNF',
                'title' => 'Monufia Rate (المنوفية)',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'EG-MT',
                'title' => 'Matrouh Rate (مطروح)',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'EG-PTS',
                'title' => 'Port Said Rate (بورسعيد)',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'EG-SHG',
                'title' => 'Sohag Rate (سوهاج)',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'EG-SHR',
                'title' => 'Sharqia Rate (الشرقية)',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'EG-SIN',
                'title' => 'North Sinai Rate (شمال سيناء)',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'EG-SUZ',
                'title' => 'Suez Rate (السويس)',
                'type' => 'text',
                'channel_based' => true,
            ],
            [
                'name' => 'EG-WAD',
                'title' => 'New Valley Rate (الوادي الجديد)',
                'type' => 'text',
                'channel_based' => true,
            ],
        ],
    ],
];
